### ISSUE TITLE
ATTiny1634 support.

### ISSUE THREAD

**Issue by colesnicov** [greiman/FreeRTOS-Arduino#13]
Hello. When trying to compile the program for the ATTiny1634 processor, I get the following error:

```
Building file: /home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/croutine.c
Starting C compile
"/home/denis/opt/eclipse//arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -mmcu=attiny1634 -DF_CPU=8000000L -DARDUINO=10802 -DARDUINO_AVR_ATTINY1634_OPTIBOOT -DARDUINO_ARCH_AVR   -I"/home/denis/opt/eclipse/arduinoPlugin/packages/ATTinyCore/hardware/avr/1.1.5/cores/tinymodern" -I"/home/denis/opt/eclipse/arduinoPlugin/libraries/ShiftRegister74HC595/1.1.0" -I"/home/denis/opt/eclipse/arduinoPlugin/libraries/ShiftRegister74HC595/1.1.0/src" -I"/home/denis/opt/eclipse/arduinoPlugin/packages/ATTinyCore/hardware/avr/1.1.5/libraries/EEPROM" -I"/home/denis/Arduino/libraries/Polymorphic_Buttons" -I"/home/denis/Arduino/libraries/Audio" -I"/home/denis/Arduino/libraries/Audio/src" -I"/home/denis/Arduino/libraries/FreeRTOS_AVR" -I"/home/denis/Arduino/libraries/FreeRTOS_AVR/src" -MMD -MP -MF"libraries/FreeRTOS_AVR/src/utility/croutine.c.d" -MT"libraries/FreeRTOS_AVR/src/utility/croutine.c.o" -D__IN_ECLIPSE__=1 "/home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/croutine.c"  -o  "libraries/FreeRTOS_AVR/src/utility/croutine.c.o"
Finished building: /home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/croutine.c
 
Building file: /home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/event_groups.c
Starting C compile
"/home/denis/opt/eclipse//arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -mmcu=attiny1634 -DF_CPU=8000000L -DARDUINO=10802 -DARDUINO_AVR_ATTINY1634_OPTIBOOT -DARDUINO_ARCH_AVR   -I"/home/denis/opt/eclipse/arduinoPlugin/packages/ATTinyCore/hardware/avr/1.1.5/cores/tinymodern" -I"/home/denis/opt/eclipse/arduinoPlugin/libraries/ShiftRegister74HC595/1.1.0" -I"/home/denis/opt/eclipse/arduinoPlugin/libraries/ShiftRegister74HC595/1.1.0/src" -I"/home/denis/opt/eclipse/arduinoPlugin/packages/ATTinyCore/hardware/avr/1.1.5/libraries/EEPROM" -I"/home/denis/Arduino/libraries/Polymorphic_Buttons" -I"/home/denis/Arduino/libraries/Audio" -I"/home/denis/Arduino/libraries/Audio/src" -I"/home/denis/Arduino/libraries/FreeRTOS_AVR" -I"/home/denis/Arduino/libraries/FreeRTOS_AVR/src" -MMD -MP -MF"libraries/FreeRTOS_AVR/src/utility/event_groups.c.d" -MT"libraries/FreeRTOS_AVR/src/utility/event_groups.c.o" -D__IN_ECLIPSE__=1 "/home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/event_groups.c"  -o  "libraries/FreeRTOS_AVR/src/utility/event_groups.c.o"
Finished building: /home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/event_groups.c
 
Building file: /home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/heap_3.c
Starting C compile
"/home/denis/opt/eclipse//arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -mmcu=attiny1634 -DF_CPU=8000000L -DARDUINO=10802 -DARDUINO_AVR_ATTINY1634_OPTIBOOT -DARDUINO_ARCH_AVR   -I"/home/denis/opt/eclipse/arduinoPlugin/packages/ATTinyCore/hardware/avr/1.1.5/cores/tinymodern" -I"/home/denis/opt/eclipse/arduinoPlugin/libraries/ShiftRegister74HC595/1.1.0" -I"/home/denis/opt/eclipse/arduinoPlugin/libraries/ShiftRegister74HC595/1.1.0/src" -I"/home/denis/opt/eclipse/arduinoPlugin/packages/ATTinyCore/hardware/avr/1.1.5/libraries/EEPROM" -I"/home/denis/Arduino/libraries/Polymorphic_Buttons" -I"/home/denis/Arduino/libraries/Audio" -I"/home/denis/Arduino/libraries/Audio/src" -I"/home/denis/Arduino/libraries/FreeRTOS_AVR" -I"/home/denis/Arduino/libraries/FreeRTOS_AVR/src" -MMD -MP -MF"libraries/FreeRTOS_AVR/src/utility/heap_3.c.d" -MT"libraries/FreeRTOS_AVR/src/utility/heap_3.c.o" -D__IN_ECLIPSE__=1 "/home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/heap_3.c"  -o  "libraries/FreeRTOS_AVR/src/utility/heap_3.c.o"
Finished building: /home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/heap_3.c
 
Building file: /home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/list.c
Starting C compile
"/home/denis/opt/eclipse//arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -mmcu=attiny1634 -DF_CPU=8000000L -DARDUINO=10802 -DARDUINO_AVR_ATTINY1634_OPTIBOOT -DARDUINO_ARCH_AVR   -I"/home/denis/opt/eclipse/arduinoPlugin/packages/ATTinyCore/hardware/avr/1.1.5/cores/tinymodern" -I"/home/denis/opt/eclipse/arduinoPlugin/libraries/ShiftRegister74HC595/1.1.0" -I"/home/denis/opt/eclipse/arduinoPlugin/libraries/ShiftRegister74HC595/1.1.0/src" -I"/home/denis/opt/eclipse/arduinoPlugin/packages/ATTinyCore/hardware/avr/1.1.5/libraries/EEPROM" -I"/home/denis/Arduino/libraries/Polymorphic_Buttons" -I"/home/denis/Arduino/libraries/Audio" -I"/home/denis/Arduino/libraries/Audio/src" -I"/home/denis/Arduino/libraries/FreeRTOS_AVR" -I"/home/denis/Arduino/libraries/FreeRTOS_AVR/src" -MMD -MP -MF"libraries/FreeRTOS_AVR/src/utility/list.c.d" -MT"libraries/FreeRTOS_AVR/src/utility/list.c.o" -D__IN_ECLIPSE__=1 "/home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/list.c"  -o  "libraries/FreeRTOS_AVR/src/utility/list.c.o"
Finished building: /home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/list.c
 
Building file: /home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/port.c
Starting C compile
"/home/denis/opt/eclipse//arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-gcc" -c -g -Os -Wall -Wextra -std=gnu11 -ffunction-sections -fdata-sections -mmcu=attiny1634 -DF_CPU=8000000L -DARDUINO=10802 -DARDUINO_AVR_ATTINY1634_OPTIBOOT -DARDUINO_ARCH_AVR   -I"/home/denis/opt/eclipse/arduinoPlugin/packages/ATTinyCore/hardware/avr/1.1.5/cores/tinymodern" -I"/home/denis/opt/eclipse/arduinoPlugin/libraries/ShiftRegister74HC595/1.1.0" -I"/home/denis/opt/eclipse/arduinoPlugin/libraries/ShiftRegister74HC595/1.1.0/src" -I"/home/denis/opt/eclipse/arduinoPlugin/packages/ATTinyCore/hardware/avr/1.1.5/libraries/EEPROM" -I"/home/denis/Arduino/libraries/Polymorphic_Buttons" -I"/home/denis/Arduino/libraries/Audio" -I"/home/denis/Arduino/libraries/Audio/src" -I"/home/denis/Arduino/libraries/FreeRTOS_AVR" -I"/home/denis/Arduino/libraries/FreeRTOS_AVR/src" -MMD -MP -MF"libraries/FreeRTOS_AVR/src/utility/port.c.d" -MT"libraries/FreeRTOS_AVR/src/utility/port.c.o" -D__IN_ECLIPSE__=1 "/home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/port.c"  -o  "libraries/FreeRTOS_AVR/src/utility/port.c.o"
/home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/port.c: In function 'prvSetupTimerInterrupt':
/home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/port.c:530:3: error: 'TIMSK0' undeclared (first use in this function)
   TIMSK0  |= (1 << OCIE0A);
   ^
/home/denis/Arduino/libraries/FreeRTOS_AVR/src/utility/port.c:530:3: note: each undeclared identifier is reported only once for each function it appears in
make: *** [libraries/FreeRTOS_AVR/src/utility/port.c.o] Error 1
```

**Comment by TamojitSaha** [comment]
You need to look at the TIMER section in data sheet of Attiny1634.
Try changing the `TIMSK0` to `TIMSK` and then post the results.  `TIMSK`  is a register which means _Timer Interrupt Mask_. It basically generates an interrupt if Compare match in Timer/Counter 0 occurs.

**Comment by TamojitSaha** [comment]
@colesnicov Please have a look at the updated comment. Hope it helps!

**Comment by colesnicov** [comment]
I'll tell you late

**Comment by greiman** [comment]
I can't help since I will not add support for new boards.

I am working on a port of FreeRTOS 10.0.  This is a very old Version 8.2.

**Comment by colesnicov** [comment]
Good evening. So I tried to fix it according to your advice:

```
static void prvSetupTimerInterrupt( void )
{
  OCR0A = 1;
#ifdef __AVR_ATtiny1634__
  TIMSK  |= (1 << OCIE0A);
#else
  TIMSK0  |= (1 << OCIE0A);
#endif
}
```

The compilation was done in order, but the application itself does not work. The planner will not start or it will be bugged elsewhere. I will not take it anymore. I will watch your repository and if you release a new version then you will see :)
